### ISSUE TITLE
1.) Bug "Youtubelink '+' erasing data" 2.)"Shouldn't there be a start and end date?"  3.) Wouldn't there be ticket link for each city's show?

### ISSUE THREAD

**Issue by MazahirHaroon** [akkshay7/Rexband-Admin#1]
Youtube + button bug, when I press once, it is working fine, but after I enter the second youtube link and press + in order to enter the third youtube link, it is erasing (replacing) data entered in the column for the second youtube
1.
![entered2ndlink](https://user-images.githubusercontent.com/19510062/27999836-da89e65a-653e-11e7-8213-6a57180467fd.png)
2.
![afteripress](https://user-images.githubusercontent.com/19510062/27999839-e3028a3a-653e-11e7-8b8c-7be877336639.png)

**Comment by akkshaylawrence** [comment]
Fixed issue in 1205fcd
